/** Declaration file generated by dts-gen */

export = delegates;

declare class delegates {
    constructor(proto: any, target: any);

    access(name: any): any;

    fluent(name: any): any;

    getter(name: any): any;

    method(name: any, ...args: any[]): any;

    setter(name: any): any;

}

declare namespace delegates {
    namespace prototype {
        function access(name: any): any;

        function fluent(name: any): any;

        function getter(name: any): any;

        function method(name: any, ...args: any[]): any;

        function setter(name: any): any;

        namespace access {
            const prototype: {
            };

        }

        namespace fluent {
            const prototype: {
            };

        }

        namespace getter {
            const prototype: {
            };

        }

        namespace method {
            const prototype: {
            };

        }

        namespace setter {
            const prototype: {
            };

        }

    }

}

